### ISSUE TITLE
您好   请问这个ip是哪里的ip，好像也不是我电脑的ip啊

### ISSUE THREAD

**Issue by 358xiaoyihezemin** [linjackson78/taro-deploy#1]
![image](https://user-images.githubusercontent.com/20399396/114139025-11790580-9941-11eb-94b3-504e16c3a0f6.png)

**Comment by linjackson78** [comment]
这个应该是你们微信小程序设置了上传程序包的白名单，不是 taro-deploy 的问题。

建议登录小程序的管理平台，改一下相关设置，可以简单地先把白名单关掉试试。或者可以查询微信的 miniprogram-ci 相关的文档看一下错误码是什么问题。

**Comment by 358xiaoyihezemin** [comment]
> 这个应该是你们微信小程序设置了上传程序包的白名单，不是 taro-deploy 的问题。
> 
> 建议登录小程序的管理平台，改一下相关设置，可以简单地先把白名单关掉试试。或者可以查询微信的 miniprogram-ci 相关的文档看一下错误码是什么问题。

把那个ip设置到白名单后就好了
